### ISSUE TITLE
JSON files dont exist

### ISSUE THREAD

**Issue by CxerizoBirb** [Regnander/stardew-valley-swedish#26]
`[Content Patcher] Can't apply load "Stardew Swedish > Various Data (Data/Blueprints)" to Data/Buildings: the FromFile file 'assets\Data\Buildings.json' doesn't exist.
[Content Patcher] Can't apply load "Stardew Swedish > Various Data (Data/Blueprints)" to Data/Buildings: the FromFile file 'assets\Data\Buildings.json' doesn't exist.
[Content Patcher] Can't apply load "Stardew Swedish > Various Data (Data/NPCDispositions)" to Data/Characters: the FromFile file 'assets\Data\Characters.json' doesn't exist.
[Content Patcher] Can't apply load "Stardew Swedish > Various Data (Data/NPCDispositions)" to Data/Characters: the FromFile file 'assets\Data\Characters.json' doesn't exist.
[Content Patcher] Can't apply load "Stardew Swedish > Various Data (Data/ObjectInformation)" to Data/Objects: the FromFile file 'assets\Data\Objects.json' doesn't exist.
[Content Patcher] Can't apply load "Stardew Swedish > Various Data (Data/BigCraftablesInformation)" to Data/BigCraftables: the FromFile file 'assets\Data\BigCraftables.json' doesn't exist.`

![image](https://github.com/Regnander/stardew-valley-swedish/assets/117398705/c38fff83-a663-4d5e-8608-ce0ff1d95c23)

I'm not sure what else to put but yeah these files dont exist when content patcher really wants them to.

Version: 1.6.3

**Comment by CxerizoBirb** [comment]
I didnt realise this mod was only compatible with the legacy version, Ignore this issue. Apologies

**Comment by Regnander** [comment]
No worries! I'm planning to add 1.6 support once I'm done translating the legacy assets.

**Comment by CxerizoBirb** [comment]
Awesome! Looking forward to it!!
